# Generated by excel_to_rpy.py
# 源文件: term_1_stage_1.xlsx


label before_konw:
    window hide
    centered "一年后的中考，\n你超常发挥，拿下了736的高分，\n顺利进入了离你家很近的重庆八中渝北校区。\n虽然你的身高还是定格在了143cm，\n但至少八中没有人会欺负你。"
    window auto
    scene black
    window hide
    centered "高一时，你远远望见一个熟悉的身影。\n你知道，他就是庄桂清。\n后来，你找了自己的表叔——徐忍，\n在高一下分班的时候，把你和庄桂清分到了一个班..."
    window auto
    window hide
    centered "{size=+20}高二下期...{/size}"
    window auto
    scene bg classroom with dissolve
    show player_block at left
    "你远远守候了他一年，"
    "始终不敢靠近。"
    "但是现在呢？[player_name]？"
    "在他和陈叙塬冷战的时候..."
    menu:
        "上前和他打招呼":
            jump t1_1
        "继续守望":
            jump bad_end_1
        "埋头学习（陆明远线 暂未开放）":
            jump lu_mingyuan_route

label t1_1:
    scene bg classroom with dissolve
    show player_block at left
    show zhuang_block at right with dissolve
    "你暗自下定决心，在心中为自己鼓气，迈出了第一步。"
    "你走到了庄桂清面前。"
    zhuang "[player_name]，你...你找我有什么事吗？"
    player_name "庄桂清？你...这是在？"
    "庄桂清猛地合上日记本，他抬头看向你。"
    zhuang "没...没什么。"
    menu:
        "没事，就是看见你在写东西，有点好奇。":
            jump t1_1_a
        "就是听说最近你和陈叙塬闹矛盾了？":
            jump t1_1_b
        "老徐让我来帮你补补功课。":
            jump t1_1_c
label t1_1_a:
    $ love_zhuang += 1
    player_name "没事，就是看见你在写东西，有点好奇。"
    player_name "就是想来问问。"
    zhuang "没啥的，随便写写。"
    zhuang "嗯...对。"
    player_name "哦哦，那有啥我能帮你的？"
    zhuang "嗯..."
    zhuang "这个生物题可以吗？"
    jump t1_2
label t1_1_b:
    player_name "就是听说你和陈叙塬闹矛盾了？"
    player_name "你们怎么回事啊？不是玩得那么好？"
    zhuang "..."
    zhuang "没啥，一点小矛盾。"
    player_name "那有什么我能帮你的？"
    zhuang "嗯..."
    zhuang "这个生物题可以吗？"
    jump t1_2
label t1_1_c:
    $ trust_zhuang += 2
    player_name "老徐让我帮你补补功课。"
    player_name "那你有哪不大会？"
    zhuang "老徐啊...谢谢你，也麻烦他了。"
    zhuang "嗯...生物的遗传题可以吗？"
    "生物吗？当然可以呀。"
    jump t1_2
label t1_2:
    window auto
    narrator "To be continued..."
    return

label bad_end_1:
    scene bg school with dissolve
    show player_block at left
    narrator "你再一次低下了头，装作什么都没看见。"
    "庄桂清和陈叙塬的冷战还在继续，"
    "而你，依然远远地看着。"
    "日复一日，年复一年。"
    "直到毕业的那天，"
    "你依然没能告诉他你的名字。"
    scene black
    window hide
    centered "{size=+20}{color=#ff0000}BAD END{/color}{/size}\n{color=#ff0000}——错过——{/color}"
    window auto
    return

label lu_mingyuan_route:
    scene bg classroom with dissolve
    show player_block at left
    show lu_block at right with dissolve
    narrator "你收回了望向庄桂清的视线。"
    scene black
    window hide
    centered "{size=+20}{color=#888}——陆明远线 暂未开放，敬请期待——{/color}{/size}"
    window auto
    return
