# Generated by excel_to_rpy.py
# 源文件: script.xlsx

define narrator = Character("")
define student_a = Character("学生A")
define student_b = Character("学生B")
define boy = Character("小男孩")
define zhuang = Character("庄桂清")
define lu = Character("陆明远")
default player_name = ""
image bg toilet = Transform("images/background/Toliet.png", size=(1920, 1080))
image bg school = Transform("images/background/School.jpg", size=(1920, 1080))
image bg classroom = Transform("images/background/Classroom.jpg", size=(1920, 1080))
image bg room_zhuang = Transform("images/background/Room_zhuang.jpg", size=(1920, 1080))
image player_block = Solid("#4a90d9", xsize=250, ysize=450)
image zhuang_block = Solid("#50c878", xsize=250, ysize=450)
image bully_block = Solid("#e74c3c", xsize=250, ysize=450)
image boy_block = Solid("#f39c12", xsize=200, ysize=350)
image lu_block = Solid("#9b59b6", xsize=250, ysize=450)

label start:
    $ preferences.text_cps = 40
    stop music fadeout 1.0
    scene bg toilet with fade
    show bully_block at center
    show bully_block as bully2 at right
    narrator "一阵又一阵的骚乱声中，你被推到了地上..."
    narrator "你抬头望去，三个凶神恶煞的高年级学生挡在了你的面前。"
    student_a "小不点？怎么都初二了还这么矮啊？你爸妈没给你吃饭啊？"
    narrator "你看见三个人围了上来，对着你拳打脚踢，又说又笑。"
    narrator "你躺在角落里瑟瑟发抖，不断抽泣着。"
    "此时，一个看着比你大了很多的小男孩突然闯了进来，他举着手机，高声大呼"
    show boy_block at left with moveinleft
    boy "我...我已经告诉老师了！...你们等着处分吧！"
    narrator "虽然他的语气中带着一些颤抖，但你却看见了他眼中的那抹光。"
    "那几个高年级学生站起来互相对视了一眼"
    student_b "小兔崽子，别让我逮到你。"
    hide bully_block
    hide bully2
    narrator "为首的那个，带着其他两个人离开了厕所。"
    show boy_block at center with move
    "你看见那个小男孩朝你走来，蹲下身，向你伸出手。"
    zhuang "你好啊，我叫庄桂清..."
    scene black
    window hide
    centered "从此，\n你认识了这个叫庄桂清的人，\n但你们的交集，\n却好像只局限在了这一次见面。\n而你...\n甚至没能告诉他你的名字..."
    window auto
    $ player_name = renpy.input("所以...你叫？").strip()
    jump stage_1_intro
