[changelog]
header = """
# Changelog\n
"""
body = """
{%- macro remote_url() -%}
  https://github.com/WhiteMoon319/TheCampusHeaven
{%- endmacro -%}

{% if version -%}
## [{{ version | trim_start_matches(pat="v") }}]({{ self::remote_url() }}/releases/tag/{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
{%- if commit.scope -%}
- **{{ commit.scope }}**: {{ commit.message }}
{%- else -%}
- {{ commit.message }}
{%- endif %}
{% endfor %}
{% endfor -%}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^feat|^add", group = "✨ 新增" },
  { message = "^fix|^bug", group = "🐛 修复" },
  { message = "^perf|^opt", group = "⚡ 优化" },
  { message = "^refactor|^rft", group = "♻️ 重构" },
  { message = "^docs|^doc", group = "📝 文档" },
  { message = "^style", group = "💄 样式" },
  { message = "^test", group = "✅ 测试" },
  { message = "^chore", group = "🔧 杂项" },
  { message = "^ci|^build", skip = true },
  { message = ".*", group = "📦 其他" },
]
tag_pattern = "v[0-9].*"
sort_commits = "newest"
